#!/bin/bash
# SPDX-License-Identifier: MIT
# Copyright (C) 2026 Philipp Kutin

set -e

assert() {
	test "$@" || (echo "assertion failed: $*" 1>&2 && false)
}

function labeled_assert() {
	local label="$1"
	shift
	test "$@" || (echo "assertion failed: $label: $*" 1>&2 && false)
}

concurrency_arg=

if [ "${1:0:2}" == '-j' ]; then
	concurrency_arg="$1"
	shift
fi

compiler_arg="$1"
compile_commands_file="$2"

if [[ -z "$compiler_arg" || -z "$compile_commands_file" ]]; then
	exec >&2
	echo "Usage: $0 [-j<concurrency>] <compiler> <compile_commands.json>"
	echo
	echo "- <compiler> may be an absolute or relative path. Each compile"
	echo "   command must start with the canonicalized <compiler>."
	echo "- <compile_commands.json> is expected to be in a specific form"
	echo "   (currently: as generated by CMake). Its directory part is"
	echo "   assumed to be the project directory. The final element of each"
	echo "   command must start with the canonicalized project directory."
	exit 1
fi

if ! compiler=$(which "$compiler_arg"); then
	echo "ERROR: '$compiler_arg' does not resolve to an executable file." >&2
	exit 1
fi

if [ ! -f "$compile_commands_file" ]; then
	echo "ERROR: '$compile_commands_file' does not exist or is not a regular file." >&2
	exit 1
fi

if ! project_dir=$(dirname "$compile_commands_file"); then
	echo "ERROR: failed obtaining directory part of '$compile_commands_file'." >&2
	exit 1
fi

if ! project_dir=$(realpath "$project_dir" 2>/dev/null); then
	echo "ERROR: failed canonicalizing '$project_dir'." >&2
	exit 1
fi

max_jobs=1

if [ -n "$concurrency_arg" ]; then
	if [[ ! "$concurrency_arg" =~ ^-j[1-9][0-9]?[+]?$ ]]; then
		echo "ERROR: malformed third argument, expecting '-j[1-9][0-9]?[+]?'." >&2
		exit 1
	fi
	if [[ "${concurrency_arg}" =~ [+]$ ]]; then
		concurrency_arg="${concurrency_arg%+}"
	fi

	max_jobs=${concurrency_arg:2}
fi

if [[ "$max_jobs" -gt 1 && "${BASH_VERSINFO[0]}" -lt 5 ]]; then
	# For 'wait -f':
	echo "ERROR: for concurrent processing, need at least Bash 5.0" >&2
	exit 1
fi

PREFIX_REGEX='^  "command": "'
SUFFIX_REGEX='",$'
REGEX="${PREFIX_REGEX}.*${SUFFIX_REGEX}"
SEDCMD="s/$PREFIX_REGEX//g; s/$SUFFIX_REGEX//g;"

if ! readarray -t commands < <(grep "$REGEX" "$compile_commands_file" | sed "$SEDCMD"); then
	echo "ERROR: failed reading compile commands." >&2
	exit 1
fi

command_count="${#commands[@]}"

if [ "$command_count" -eq 0 ]; then
	echo "WARNING: no compile commands." >&2
	exit 0
fi

if [ "$max_jobs" -gt "$command_count" ]; then
	max_jobs="$command_count"
fi

### 1. Validate expectations on the command strings, then prepare array 'new_args_lists'.

compiler_len="${#compiler}"
compiler_len_p1=$((compiler_len + 1))
new_args_lists=()
source_files=()

function error_and_exit() {
	local cmd="$1"
	local msg="$2"
	labeled_assert msg -n "$msg"
	labeled_assert cmd -n "$cmd"
	exec >&2
	echo "ERROR: $msg."
	echo " NOTE: fails: $cmd"
	exit 2
}

function extract_arguments() {
	local ci="$1"
	labeled_assert extract_arguments:ci -n "$ci"
	local command="${commands[$ci]}"

	local new_args=()
	# Drop the first element of the command (the path to the compiler executable):
	local state=SKIP_NEXT
	local had_arg_c=

	for word in $command; do
		if [ "$state" == SKIP_NEXT ]; then
			state=
		elif [ "$state" == EXPECT_FINAL_ARG ]; then
			project_dir_len="${#project_dir}"
			project_dir_len_p1=$((project_dir_len + 1))
			if [ "${word:0:$project_dir_len_p1}" != "$project_dir/" ]; then
				error_and_exit "$command" "for all commands, the item following '-c' must start with '$project_dir/'"
			fi
			source_files+=("$word")
			state=EXPECT_END
		elif [ "$state" == EXPECT_END ]; then
			error_and_exit "$command" "all commands must end in '-c <arg>'"
		elif [ "$word" == '-o' ]; then
			state=SKIP_NEXT
		elif [ "$word" != '-c' ]; then
			new_args+=("$word")
		else
			had_arg_c=true
			new_args+=('-E')  # --preprocess: Only run the preprocessor
			new_args+=('-H')  # --trace-includes: Show header includes and nesting depth
			state=EXPECT_FINAL_ARG
		fi
	done

	if [ -z "$had_arg_c" ]; then
		error_and_exit "$command" "all commands must contain '-c'"
	fi

	new_args_lists+=("${new_args[*]}")
}

# We *want* the backslash:
# shellcheck disable=1003
BS='\'
DQ='"'
escaped_BS="$BS$BS"
escaped_DQ="$BS$BS$DQ"

for ci in "${!commands[@]}"; do
	command="${commands[$ci]}"
	if [ "${command:0:$compiler_len_p1}" != "$compiler " ]; then
		error_and_exit "$command" "all commands must start with '$compiler '"
	elif [[ "$command" =~ \\ ]]; then
		command=${command//"$escaped_BS"/$BS}
		command=${command//"$escaped_DQ"/$DQ}
		if [[ "$command" =~ \\ ]]; then		
			error_and_exit "$command" "no command may contain a backslash, except before another one or a double quote"
		fi
	fi

	extract_arguments "$ci"
done

new_command_count="${#new_args_lists[@]}"
unset command_count
unset commands

### 2. Functions common to serial and concurrent cases

to_replace=" $project_dir/"

function echo_without_prefix() {
	echo "${1/$to_replace/ }"
}

function grep_and_strip() {
	while read -r line; do
		# We *want* to match literally:
		# shellcheck disable=SC2076
		if [[ "$line" =~ "$to_replace" ]]; then
			echo_without_prefix "$line"
		fi
	done
}

function process_translation_unit() {
	local ci="$1"
	labeled_assert process_translation_unit:ci -n "$ci"
	local new_args_str="${new_args_lists[ci]}"

	# shellcheck disable=SC2206
	local new_args=($new_args_str)
	local new_args_count="${#new_args[@]}"
	labeled_assert new_args_count "$new_args_count" -ge 3
	for ((i = 0; i < 3; i++)) do
		unset new_args[new_args_count - 1 - i]
	done
	printf "# [TU_%d] %s\n" $((ci + 1)) "${new_args[*]}"

	local source_file="${source_files[ci]}"
	echo -n "="
	echo_without_prefix " $source_file"
	# We *want* to word-split 'new_args_str':
	# shellcheck disable=SC2086
	("$compiler" $new_args_str "$source_file" >/dev/null) 2>&1 | grep_and_strip
	exit_code="${PIPESTATUS[0]}"
	echo
	return "$exit_code"
}

### 3. Invoke compiler with prepared commands and filter its output

if [ "$max_jobs" -eq 1 ]; then
	## Serial processing
	for ci in "${!new_args_lists[@]}"; do
		if process_translation_unit "$ci"; then true; else
			exit $?
		fi
	done
	exit 0
fi

## Concurrent processing

# An earlier revision of this script contained an implementation using 'coproc'. This did
# not work out well. The initial assumption was that the following is possible from Bash:
#
#  1. Have an anonymous pipe for child->parent process communication -> yes.
#  2. Being able to read from it after the child has terminated AND the parent has 'waited'
#     for it to gather its exit status (POSIX waitpid(), Bash 'wait') -> NO!
#
# Point 2 seems intuitively expected, even after waiting. The expectation is that the pipe
# as a resource is managed independently of the process: as long as the parent has not
# closed the read end of the pipe, it is possible to obtain from it the unread tail of what
# the child has written into it.
#
# However, this behavior is not mimicked by the Bash builtin 'coproc'. Example:
#
#  $ coproc COPROC { echo qwe; sleep 10; }
#  $ pid=$COPROC_PID && test -n $pid
#  $ echo $?
#  0
#  $ read_fd=${COPROC[0]}
#  $ echo $read_fd
#  63
#  $ sleep 10  # Wait for the child to exit, but do not 'wait'.
#  $ echo $COPROC_PID  # -> empty, cleared from under our feet
#  $ echo ${COPROC[@]} # -> dito
#  $ read -r -u $read_fd
#  bash: read: 63: invalid file descriptor: Bad file descriptor
#
#
# Thus began a journey of workarounds.
#
# Idea A: when a child is done, it communicates this fact to the parent by stopping itself
#  -- sending itself a SIGSTOP signal. However, The Bash 'wait' builtin *cannot* be used to
#  wait for a running->stopped state change. (With only one process for testing purposes,
#  it returns with code 127.) From the documentation:
#
#   If the -n option is supplied, `wait` waits for any one of the given ids or, if no
#   ids are supplied, any job or process substitution, to complete and returns its exit
#   status. If none of the supplied ids is a child of the shell, or if no ids are
#   supplied and the shell has no unwaited-for children, the exit status is 127.
#
# Workaround A.1: Resort to periodic polling. Worked, but it was not pretty.
#
#
#  ... A few steps back, why the STOP -> CONT dance at all? Well, as far as I can see,
#  lack of good alternatives.
#
#  1. (See 'coproc' example above)
#  2. Bash does not expose 'poll()' to wait for availability of data to read.
#
#  ... We *could* go another route and use one sink for the different sources.
#  Then we'd have to implement some kind of "protocol" to reassemble fragments.
#  Up-front, the many-file-descriptor solution seemed easier. Not so sure now...
#
# Q: Why not: create a pipe up-front (named first, file removed to only keep the
#    descriptor), use that as control mechanism children -> parent?
# A: Tried that. Got into trouble at spawning the first child of the follow-up batch
#    ('coproc' failed -- none of the out-vars were set; inconsistently, $? was 0).
#    Did not have time to pursue debugging.

labeled_assert max_jobs "$max_jobs" -ge 2

# Report string sizes in bytes:
export LANG=C
export LC_ALL=C

# We are Linux-only for now. See 'man 7 pipe':
#
#  POSIX.1 says that writes of less than PIPE_BUF bytes must be atomic: (...).
#  (On Linux, PIPE_BUF is 4096 bytes.)
#
# and in section "Pipe capacity"
#
#  Since Linux 2.6.11, the pipe capacity is 16 pages (...). Since Linux 4.5, the default
#  pipe capacity is lower than 16 pages when the pipe-user-pages-soft limit is exceeded.
#
# Also, from Linux 'Documentation/admin-guide/sysctl/fs.rst':
#
#  pipe-user-pages-soft
#  --------------------
#
#  Maximum total number of pages a non-privileged user may allocate for pipes
#  before the pipe size gets limited to a single page. (...)

PIPE_BUF=4096

g_pids=()

to_reap_count=0

# ----------

function process_tu() {
	ci="$1"

	local result
	if result=$(process_translation_unit "$ci"); then true; else
		local exit_code=$?
		echo "ERROR: command $ci: compiler returned exit code $exit_code" >&2
		exit "$exit_code"
	fi

	# Check if we can write "$result\n\n" without blocking.
	result_size="${#result}"

	if [ "$result_size" -ge $((PIPE_BUF - 1)) ]; then
		echo "NYI: command $ci: result too large: $result_size" >&2
		exit 100
	fi

	# The following should not block:
	printf "%s\n\n" "$result"
}

function find_command_index() {
	local pid="$1"
	labeled_assert find_command_index:pid -n "$pid"
	pid_count="${#g_pids[@]}"

	for ((i=0; i < pid_count; i++)); do
		if [ "${g_pids[i]}" -eq "$pid" ]; then
			echo "$i"
			return
		fi
	done

	assert -z unreachable
	exit 101
}

function spawn_coprocess() {
	local ci="$1"
	labeled_assert spawn_coprocess:ci -n "$ci"

	process_tu "$ci" &
	local pid=$!
	to_reap_count=$((to_reap_count + 1))
	g_pids[ci]="$pid"
}

function update_max_exit_code() {
	local exit_code="$1"
	labeled_assert exit_code -n "$exit_code"

	if [ "$exit_code" -gt "$max_exit_code" ]; then
		max_exit_code="$exit_code"
	fi
}

# ----------

for ((ci=0; ci < max_jobs; ci++)); do
	spawn_coprocess "$ci"
done

labeled_assert to_reap_count "$to_reap_count" -eq "$max_jobs"

max_exit_code=0
ci="$max_jobs"

while [ "$to_reap_count" -gt 0 ]; do
	wait -nf -p stopped_pid
	exit_code=$?
	update_max_exit_code "$exit_code"

	to_reap_count=$((to_reap_count - 1))

	# If we can, first spawn a new child.
	if [ "$ci" -lt "$new_command_count" ]; then
		spawn_coprocess "$ci"
		ci=$((ci + 1))
	fi

	# Take care of the terminated one.

	labeled_assert stopped_pid -n "$stopped_pid"
	finished_ci=$(find_command_index "$stopped_pid")

	g_pids[finished_ci]=-1
done

exit "$max_exit_code"
