#!/bin/bash
# SPDX-License-Identifier: MIT
# Copyright (C) 2026 Philipp Kutin

set -e

assert() {
	test "$@" || (echo "assertion failed: $*" 1>&2 && false)
}

concurrency_arg=

if [ "${1:0:2}" == '-j' ]; then
	concurrency_arg="$1"
	shift
fi

compiler_arg="$1"
compile_commands_file="$2"

if [[ -z "$compiler_arg" || -z "$compile_commands_file" ]]; then
	exec >&2
	echo "Usage: $0 [-j<concurrency>] <compiler> <compile_commands.json>"
	echo
	echo "- <compiler> may be an absolute or relative path. Each compile"
	echo "   command must start with the canonicalized <compiler>."
	echo "- <compile_commands.json> is expected to be in a specific form"
	echo "   (currently: as generated by CMake). Its directory part is"
	echo "   assumed to be the project directory. The final element of each"
	echo "   command must start with the canonicalized project directory."
	echo "   Note: this includes symlinks being resolved."
	exit 1
fi

if ! compiler=$(which "$compiler_arg"); then
	echo "ERROR: '$compiler_arg' does not resolve to an executable file." >&2
	exit 1
fi

if ! compile_commands_file=$(realpath "$compile_commands_file" 2>/dev/null); then
	echo "ERROR: failed canonicalizing '$compile_commands_file'." >&2
	exit 1
fi

if ! project_dir=$(dirname "$compile_commands_file"); then
	echo "ERROR: failed obtaining directory part of '$compile_commands_file'." >&2
	exit 1
fi

max_jobs=1
if [ -n "$concurrency_arg" ]; then
	if [[ ! "$concurrency_arg" =~ ^-j[1-9][0-9]?$ ]]; then
		echo "ERROR: malformed third argument, expecting '-j[1-9][0-9]?'." >&2
		exit 1
	fi
	max_jobs=${concurrency_arg:2}
fi

PREFIX_REGEX='^  "command": "'
SUFFIX_REGEX='",$'
REGEX="${PREFIX_REGEX}.*${SUFFIX_REGEX}"
SEDCMD="s/$PREFIX_REGEX//g; s/$SUFFIX_REGEX//g;"

if ! readarray -t commands < <(grep "$REGEX" "$compile_commands_file" | sed "$SEDCMD"); then
	echo "ERROR: failed reading compile commands." >&2
	exit 1
fi

command_count="${#commands[@]}"

if [ "$command_count" -eq 0 ]; then
	echo "WARNING: no compile commands." >&2
	exit 0
fi

### 1. Validate expectations on the command strings, then prepare array 'new_args_lists'.

compiler_len="${#compiler}"
compiler_len_p1=$((compiler_len + 1))
new_args_lists=()
source_files=()

function error_and_exit() {
	local cmd="$1"
	local msg="$2"
	assert -n "$msg"
	assert -n "$cmd"
	exec >&2
	echo "ERROR: $msg."
	echo " NOTE: fails: $cmd"
	exit 2
}

function extract_arguments() {
	local ci="$1"
	assert -n "$ci"
	local command="${commands[$ci]}"

	local new_args=()
	# Drop the first element of the command (the path to the compiler executable):
	local state=SKIP_NEXT
	local had_arg_c=

	for word in $command; do
		if [ "$state" == SKIP_NEXT ]; then
			state=
		elif [ "$state" == EXPECT_FINAL_ARG ]; then
			project_dir_len="${#project_dir}"
			project_dir_len_p1=$((project_dir_len + 1))
			if [ "${word:0:$project_dir_len_p1}" != "$project_dir/" ]; then
				error_and_exit "$command" "for all commands, the item following '-c' must start with '$project_dir/'"
			fi
			source_files+=("$word")
			state=EXPECT_END
		elif [ "$state" == EXPECT_END ]; then
			error_and_exit "$command" "all commands must end in '-c <arg>'"
		elif [ "$word" == '-o' ]; then
			state=SKIP_NEXT
		elif [ "$word" != '-c' ]; then
			new_args+=("$word")
		else
			had_arg_c=true
			new_args+=('-E')  # --preprocess: Only run the preprocessor
			new_args+=('-H')  # --trace-includes: Show header includes and nesting depth
			state=EXPECT_FINAL_ARG
		fi
	done

	if [ -z "$had_arg_c" ]; then
		error_and_exit "$command" "all commands must contain '-c'"
	fi

	new_args_lists+=("${new_args[*]}")
}

for ci in "${!commands[@]}"; do
	command="${commands[$ci]}"
	if [ "${command:0:$compiler_len_p1}" != "$compiler " ]; then
		error_and_exit "$command" "all commands must start with '$compiler '"
	elif [[ "$command" =~ \\ ]]; then
		error_and_exit "$command" "no command may contain a backslash"
	fi

	extract_arguments "$ci"
done

### 2. Functions common to serial and concurrent cases

to_replace=" $project_dir/"

function echo_without_prefix() {
	echo "${1/$to_replace/ }"
}

function grep_and_strip() {
	while read -r line; do
		# We *want* to match literally:
		# shellcheck disable=SC2076
		if [[ "$line" =~ "$to_replace" ]]; then
			echo_without_prefix "$line"
		fi
	done
}

function process_translation_unit() {
	local ci="$1"
	assert -n "$ci"
	local new_args_str="${new_args_lists[ci]}"
	local source_file="${source_files[ci]}"
	echo -n "="
	echo_without_prefix " $source_file"
	# We *want* to word-split 'new_args_str':
	# shellcheck disable=SC2086
	("$compiler" $new_args_str "$source_file" >/dev/null) 2>&1 | grep_and_strip
	exit_code="${PIPESTATUS[0]}"
	echo
	return "$exit_code"
}

### 3. Invoke compiler with prepared commands and filter its output

if [ "$max_jobs" -eq 1 ]; then
	## Serial processing
	for ci in "${!new_args_lists[@]}"; do
		if ! process_translation_unit "$ci"; then
			exit $?
		fi
	done
	exit 0
fi

## Concurrent processing
