FROM @ARCH@/@DISTRO_IMAGE@

LABEL maintainer="Philipp Kutin <philipp.kutin@gmail.com>"

#@if-foreign:COPY /qemu-@qemu-suffix@ /usr/local/bin

@DO_update_packages@

# Common:
RUN @install@ git make mg
# For building LuaJIT:
RUN @install@ gcc $pkg_libc_dev

RUN @adduser@ user

USER user
WORKDIR /home/user

########## Check out, build and install LuaJIT 2.1 ##########

# Make sure that a fast-forward re-clones the repo:
RUN echo @LUAJIT_GIT_HASH@
RUN git clone https://github.com/LuaJIT/LuaJIT.git \
    --single-branch --branch=v2.1 --shallow-since=2022-08-01 \
    ./luajit-2.1
RUN (cd luajit-2.1 && git checkout @LUAJIT_GIT_HASH@)

WORKDIR /home/user/luajit-2.1
RUN make -j4
RUN sha256sum src/luajit | grep -q @LUAJIT_SHA256@
USER root
RUN make install
RUN ln -s /usr/local/bin/luajit-2.1.0-beta3 /usr/local/bin/luajit
USER user

WORKDIR /home/user

########## LJClang cloned from the build context ##########

# Install prerequisites
USER root
RUN @install@ bash
RUN @install@ $pkg_libclang_dev

# For LJClang tests:
RUN @install@ $pkg_luarocks
# NOTE: CFLAGS=-I/usr/local/include/luajit-2.1 before 'luarocks-5.1' does not work:
RUN @install@ $pkg_liblua51_dev
#
USER user
RUN @luarocks@ --local install busted

COPY /ljclang.git/ ./ljclang.git/
# Create a non-bare repository:
RUN git clone ./ljclang.git ./ljclang
WORKDIR ljclang

# Do not install llvm-dev, do not rely on llvm-config. (See 'sed -i' invocations below.)
# On Alpine Linux, clang-c/Index.h is in /usr/include and libclang.so is in /usr/lib.
#  Using 'llvm-config' of package 'llvm-dev' would wrongly point us to /usr/lib/llvm9.
# This has not been re-checked for Alpine 3.12 (which ships with LLVM 10) but in any case,
# it is nice to avoid the big package if it's not really necessary.
#
# TODO in ljclang:
#  - remove altogether in favor of an alternative detection scheme that addresses all
#    now supported distributions (Ubuntu, Raspberry Pi OS 32-bit, Alpine Linux)?
ENV LLVM_CONFIG=true

WORKDIR /home/user/ljclang
# NOTE: The binary directory is relevant only for the install targets.
RUN sed -i 's|llvm_version :=.*|llvm_version := @llvm_version@|' ./Makefile
RUN sed -i 's|bindir :=.*|bindir := /does-not-exist-and-not-relevant-here|' ./Makefile
RUN sed -i 's|incdir :=.*|incdir := @llvm_incdir@|' ./Makefile
RUN sed -i 's|libdir :=.*|libdir := @llvm_libdir@|' ./Makefile

RUN touch ./dev/createheader.lua  # force re-generation of 'ljclang_Index_h.lua'
RUN make apps

# Run the LJClang tests.
WORKDIR /home/user/ljclang
RUN LJCLANG_TESTS_NO_CXX_STDLIB=1 TEST_LOOP_COUNT=20 make test-loop

WORKDIR /home/user

##########

ENTRYPOINT ["/bin/@SHELL@"]
