FROM @ARCH@/alpine:3.12.0

LABEL maintainer="Philipp Kutin <philipp.kutin@gmail.com>"

# Common:
RUN apk add git make mg
# For building LuaJIT:
RUN apk add gcc libc-dev

RUN adduser -D user

USER user
WORKDIR /home/user

########## Check out, build and install LuaJIT 2.1 ##########

RUN git clone https://github.com/LuaJIT/LuaJIT.git \
    --single-branch --branch=v2.1 --shallow-since=2020-08-01 \
    ./luajit-2.1
RUN (cd luajit-2.1 && git checkout @LUAJIT_GIT_HASH@)

WORKDIR /home/user/luajit-2.1
RUN make -j4
RUN sha256sum src/luajit | grep -q @LUAJIT_SHA256@
USER root
RUN make install
RUN ln -s /usr/local/bin/luajit-2.1.0-beta3 /usr/local/bin/luajit
USER user

WORKDIR /home/user

########## LJClang cloned from the build context ##########

# Install prerequisites
USER root
RUN apk add bash
RUN apk add clang-dev
USER user

COPY / .
# Create a non-bare repository:
RUN git clone --depth=1 ./ljclang.git ./ljclang
WORKDIR ljclang

# Do not install llvm-dev, do not rely on llvm-config. (See 'sed -i' invocations below.)
# On Alpine Linux, clang-c/Index.h is in /usr/include and libclang.so is in /usr/lib.
#  Using 'llvm-config' of package 'llvm-dev' would wrongly point us to /usr/lib/llvm9.
# This has not been re-checked for Alpine 3.12 (which ships with LLVM 10) but in any case,
# it is nice to avoid the big package if it's not really necessary.
#
# TODO in ljclang:
#  - remove altogether in favor of an alternative detection scheme that addresses all
#    now supported platforms (Ubuntu x86_64, Raspberry Pi OS 32-bit, Alpine Linux here)?
ENV LLVM_CONFIG=true

WORKDIR /home/user/ljclang
RUN sed -i 's|llvm_version :=.*|llvm_version := 10.0.0|' ./Makefile
RUN sed -i 's|bindir :=.*|bindir := /usr/bin|' ./Makefile
RUN sed -i 's|incdir :=.*|incdir := /usr/include|' ./Makefile
RUN sed -i 's|libdir :=.*|libdir := /does-not-exist-and-is-not-relevant-here|' ./Makefile

RUN make apps

# Run the LJClang tests.
USER root
RUN apk add luarocks5.1
# NOTE: CFLAGS=-I/usr/local/include/luajit-2.1 before 'luarocks-5.1' does not work:
RUN apk add lua5.1-dev
USER user
RUN luarocks-5.1 --local install busted
#
WORKDIR /home/user/ljclang
RUN LJCLANG_TESTS_NO_CXX_STDLIB=1 make test

WORKDIR /home/user

##########

ENTRYPOINT ["/bin/sh"]
